import Head from 'next/head'
import clientPromise from './../lib/mongodb'
import MainPage from './home';

export default function Home({ res }) {
  console.log('res', res)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPage users={res} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  try {
    const client = await clientPromise;
    const db = client.db("doctor_list")
    const res = await db.collection('doctors').find()
      .toArray()
    return {
      props: { res: JSON.parse(JSON.stringify(res)) },
    }
  } catch (e) {
    return {
      props: {},
    }
  }
}