import Head from 'next/head'
import Navbar from './navbar'
import Footer from './footer'
import { createContext, useRef, useState } from 'react';
import { Field, Form, Formik } from 'formik';
import { AiOutlineCloudUpload } from 'react-icons/ai'

export const Context = createContext({})

export default function Home() {
  const [file, setFile] = useState('')
  const addProject = async (values) => {
    const res = await fetch('http://localhost:3001/api/daily', {
      method: 'post',
      body: JSON.stringify(values)
    })
  }

  const formRef = useRef()

  const onSubmit = (e, submitProps) => {
    addProject(e)
    submitProps.resetForm()
    setFile('')
  }
  return (
    <Context.Provider value={''}>
      <Head>
        <title>Create Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" referrerPolicy="no-referrer" />
      </Head>
      <div className={'bg-white text-[#262d3d]'}>
        <main className='max-w-[1440px] mx-auto'>
          <Navbar />
          <div className="flex w-full h-screen items-center justify-center">
            <Formik
              innerRef={formRef}
              onSubmit={onSubmit}
              initialValues={{ name: '', description: '', imageUrl: '' }} >
              <Form>
                <div className="shadow-xl rounded-xl px-4 py-8 flex flex-col">
                  <h1 className="title">Create Project</h1>
                  <Field
                    id='name'
                    name='name'
                    type="text"
                    className="border py-2 px-3 rounded-full mt-2 outline-none"
                    placeholder="Project Name" />
                  <Field
                    id='description'
                    name='description'
                    type="text"
                    className="border py-2 px-3 rounded-full mt-2 outline-none"
                    placeholder="Project Description" />
                  <div className="flex items-center">
                    {file ?
                      <img src={file} alt="file" className="w-full mt-6 border border-black py-4 px-6 max-h-40 object-contain" />
                      : <>
                        <input type="file"
                          name='imageUrl'
                          id="imageUrl"
                          onChange={(e) => {
                            setFile(URL.createObjectURL(e.target.files[0]))
                            formRef.current.setFieldValue('imageUrl', JSON.stringify(e.target.files[0]))
                          }}
                          className='absolute md:w-96 w-full mt-4 h-12 opacity-0 cursor-pointer' />
                        <button className="bg-gray-300 md:w-96 rounded-xl w-full mt-4 font-semibold justify-center text-18 py-2 flex items-center">
                          <AiOutlineCloudUpload className="mr-2 w-8 h-8" />
                          <span>Upload Image</span>
                        </button>
                      </>
                    }

                  </div>
                  <button type="submit" className="bg-blue-600  text-white md:w-96 rounded-xl w-full mt-16 font-semibold text-18 py-2">Create Project</button>
                </div>
              </Form>
            </Formik>
          </div >
          <Footer />
        </main>
      </div>
    </Context.Provider>
  );
}